language: node_js
node_js:
  - "8.0"
  - "6.0"
env:
  global:
    - CODECLIMATE_REPO_TOKEN=92c3b08c8527bde41420881b99483ee66c514018d6da46fc9f3f58b31d11b274
addons:
  code_climate:
    repo_token: 92c3b08c8527bde41420881b99483ee66c514018d6da46fc9f3f58b31d11b274
after_success:
  - npm install -g codeclimate-test-reporter
  - codeclimate-test-reporter < coverage/lcov.info